<a href="https://colab.research.google.com/github/Iqbal-khatoon/Numpy-and-Pandas-for-Data-Analysis/blob/master/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Hands On!**

In [ ]:
import numpy as np

Basics of Numpy Arrays

In [ ]:
x = np.array([1,2,3,4, 5,6])

#accessing individual elements
x[0] , x[1] , x[2]

(1, 2, 3)

In [ ]:
#slicing
x = np.array([1,2,3,4,5,6])

print(x[0:])

print(x[1:3])

print(x[1:-1])
print(x[:])
print(x[2::2])

[1 2 3 4 5 6]
[2 3]
[2 3 4 5]
[1 2 3 4 5 6]
[3 5]


In [ ]:
y = np.array([0, .5, 1, 1.5, 2])
#accessing multiple elements
y[0], y[2], y[-1]

(0.0, 1.0, 2.0)

In [ ]:
b = y[[0,2,-1]]
#result is an other numpy array not an individual elements
#fast processing again
print(b)


[0. 1. 2.]


Array Types

In [ ]:
print(x.dtype)
print(y.dtype)

int64
float64


**Dimension and shapes**


In [ ]:
#two dimnesional arrays
twod= np.array([[1,2,3],
          [3,6,9]])
print(twod)

[[1 2 3]
 [3 6 9]]


In [ ]:
print(twod.shape)
print(twod.ndim)
print(twod.size)

(2, 3)
2
6


In [ ]:
#square matrix
i= np.array([
          #   0,1,2
             [1,2,3], #0
             [4,5,6], #1
             [7,8,9]  #2
             ])
print(i[1])

print(i[2,2])

[4 5 6]
9


In [ ]:
#slicing
print(i[0:2])

[[1 2 3]
 [4 5 6]]


In [ ]:
#all rows first two elements
print(i[:,:2])

[[1 2]
 [4 5]
 [7 8]]


In [ ]:
print(i[:2, :1])

[[1]
 [4]]


In [ ]:
i[2] = 12
print(i)

[[ 1  2  3]
 [ 4  5  6]
 [12 12 12]]


In [ ]:
#sumarry statistics

In [ ]:
print(i.sum())
print(i.mean())
print(i.std())

57
6.333333333333333
4.242640687119285


In [ ]:
j= np.array([
          #   0,1,2
             [1,2,3], #0
             [4,5,6], #1
             [7,8,9]  #2
             ])

print(j.sum(axis =0))
print(j.sum(axis =1))

[12 15 18]
[ 6 15 24]


In [ ]:
# Create list
list1 = [180, 215, 210, 210, 188, 176, 209, 200]


# Import the numpy package as np
import numpy as np 

# Create a numpy array from list
np_list= np.array(list1)

np_list_new = np_list - 5
print(np_list_new)

[175 210 205 205 183 171 204 195]


In [ ]:
print(list1)

[180, 215, 210, 210, 188, 176, 209, 200]


In [ ]:
# Create list
marks = [180, 215, 210, 210, 188, 176, 209, 200]


# Import the numpy package as np
import numpy as np 

# Create a numpy array from list
np_marks= np.array(marks)

np_marks_new = np_marks * 2
print(np_marks_new)

[360 430 420 420 376 352 418 400]


In [ ]:
med = np.mean(np_marks)
print("Mean: " + str(med))

Mean: 198.5


In [ ]:
#last but not least performsnce is very important

l1 = list(range(1000))
#print(l1)
a = np.arange(1000)
print(type(a))

<class 'numpy.ndarray'>


In [ ]:
%time np.sum(a**2)

CPU times: user 625 µs, sys: 97 µs, total: 722 µs
Wall time: 652 µs


332833500

In [ ]:
%time sum([x**2 for x in l1])

CPU times: user 216 µs, sys: 33 µs, total: 249 µs
Wall time: 253 µs


332833500